board/urls.py
# 2015244044 이준희
# 자유게시판 및 댓글 및 문의하기 경로
from django.urls import path
from .import views

urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('post_create/', views.post_create, name="post_create"),
    path('post_detail/<int:id>/', views.post_detail, name="post_detail"),
    path('post_update/<int:id>/', views.post_update, name="post_update"),
    path('post_delete/<int:id>/', views.post_delete, name="post_delete"),
    path('comment_create/<int:id>', views.comment_create, name="comment_create"),
    path('comment_update/<int:id>/', views.comment_update, name="comment_update"),
    path('comment_delete/<int:id>/', views.comment_delete, name="comment_delete"),
    path('secret_list/', views.secret_list, name="secret_list"),
    path('secret_create/', views.secret_create, name="secret_create"),
    path('secret_detail/<int:id>/', views.secret_detail, name="secret_detail"),
    path('secret_delete/<int:id>/', views.secret_delete, name="secret_delete"),

]

main/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('about/', views.about, name="about"),

]

sunmoonbus/urls.py
# 2015244044 이준희
# 전체페이지 경로
from django.contrib import admin
from django.urls import path,include
import main.views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.index,name="index"),
    path('index/',include('main.urls')),
    path('board/',include('board.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:user_id>/reservation/', main.views.busSelect, name="busSelect"),
    path('<str:user_id>/reservation/<int:bus_id>/', main.views.startselect, name='startTime'),
    path('<str:user_id>/reservation/<int:bus_id>/<str:start_id>/', main.views.seatSelect, name='seat'),
    path('<str:user_id>/reservation/<int:bus_id>/<str:start_id>/<int:seat_id>/', main.views.confirm, name='confirm'),
    path('<str:user_id>/myhistory/', main.views.myhistory),
    path('<str:user_id>/cancel/<str:reservation_id>', main.views.cancel),
    path('initial/', main.views.initial),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

board/models.py
# 2015244044 이준희
# 블로그,댓글,문의하기 데이터베이스
from django.db import models
from accounts.models import *
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to="images/post",blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.author

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
    def __str__(self):
        return self.author

class SecretBorad(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    image=models.ImageField(upload_to="images/secret",blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

class SecretComment(models.Model):
    secretborad = models.ForeignKey('SecretBorad', on_delete=models.CASCADE,related_name='SecretComment')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
        
    class Meta:
        ordering = ['-created_at']

board/forms.py
# 2015244055 김성민
# DB에서 받은 객체를 페이지에 보여주기 
from django import forms
from .models import Post,SecretBorad

class Postform(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']
        title = forms.CharField(
            widget=forms.Textarea(attrs={'class': 'post_create'}
        )
        )
        content = forms.CharField(widget=forms.Textarea(attrs={'class': 'post_create',
        'rows': 5,
        'cols': 50, }
    )
        )

        labels = {
            'title': '제목',
            'content': '내용',
            'image': '사진',
        }
        required = {
            
            'image':False,
        }

class SecretForm(forms.ModelForm):
    class Meta:
        model = SecretBorad
        fields = ['title','content','image','private']
        title = forms.CharField(
            widget=forms.Textarea(attrs={'class': 'post_create'}
        )
        )
        content = forms.CharField(widget=forms.Textarea(attrs={'class': 'post_create',
        'rows': 5,
        'cols': 50, }
    )
        )
        labels = {
            'title': '제목',
            'content': '내용',
            'image': '사진',
            'private': '비밀글 체크',
        }
        required = {
            'image':False,
            'private':False,
        }

board/views.py
from django.shortcuts import render

# Create your views here.
# 2015244044 이준희
from django.shortcuts import render,redirect, get_object_or_404,Http404
from .forms import *
from django.utils import timezone
from board.models import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
NUM_ITEMS = 5

# 자유게시판 목록
def post_list(request):
    borads = Post.objects.all()
    list = request.GET.get('list')
    if list:
        borads =borads.filter(title__contains = list)
    page = request.GET.get('page', 1)
    paginator = Paginator(borads.order_by('-created_at'), NUM_ITEMS)
    try:
        borads = paginator.page(page)
    except PageNotAnInteger:
        borads = paginator.page(1)
    except EmptyPage:
        borads = paginator.page(paginator.num_pages)
    return render(request,"post_list.html",{'item_page_offset': borads.paginator.num_pages - borads.number,"borads":borads})

#자유게시판 생성
@login_required
def post_create(request):
    if request.method=="POST":
        form = Postform(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_at = timezone.now()
            post.author=request.user
            post.save()
            return redirect('post_list')
    elif request.method=="GET":
        form = Postform()
        return render(request, "post_create.html",{"form":form})

#자유게시판 목록
@login_required
def post_detail(request,id):
    post = get_object_or_404(Post, pk=id)
    comments = Comment.objects.filter(post=post.id)
    return render(request,"post_detail.html",{"post":post,"comments":comments})

#자유게시판 수정하기
@login_required
def post_update(request,id):
    if request.method == "GET":
        post = get_object_or_404(Post, pk=id)
        form = Postform(instance=post)
        return render(request, "post_update.html",{"form":form,"post":post})
    elif request.method == "POST":
        post = get_object_or_404(Post, pk=id)
        form = Postform(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
        return redirect("post_detail",id)
    return Http404()

#자유게시판 삭제
@login_required
def post_delete(request,id):
    post = get_object_or_404(Post,pk=id)
    if post.author != request.user:
        return redirect("main")
    post.delete()
    return redirect("post_list")

#댓글 생성
@login_required
def comment_create(request,id):
    if request.method=='POST':
        comment = Comment()
        comment.message = request.POST["message"]
        comment.post = get_object_or_404(Post, pk=id)
        comment.author = request.user
        comment.save()        
        return redirect("post_detail",id)
    return redirect("post_detail",id)

#댓글 삭제
@login_required
def comment_delete(request,id):
    comment = get_object_or_404(Comment,pk=id)
    if comment.author != request.user:
        return redirect("post_list")
    if request.method=='POST':
        comment_pk=comment.post.id
        comment.delete()
        return redirect("post_detail",comment_pk)
    return redirect("post_detail",comment_pk)
    
#댓글 수정
@login_required
def comment_update(request, id):
    comment=get_object_or_404(Comment, pk=id)   
    if comment.author != request.user:
        return redirect("index")
    if request.method=='POST':
        comment.message=request.POST["message"]
        comment_pk=comment.post.pk
        comment.save()
        return redirect("post_detail", id=comment_pk)
    elif request.method == 'GET':
        return render(request, "comment_update.html", {"comment": comment})

#문의하기 목록
def secret_list(request):
    secrets = SecretBorad.objects.all()
    list = request.GET.get('list')
    if list:
        secrets = secrets.filter(title__contains = list)
    page = request.GET.get('page', 1)
    paginator = Paginator(secrets.order_by('-created_at'), NUM_ITEMS)
    try:
        secrets = paginator.page(page)
    except PageNotAnInteger:
        secrets = paginator.page(1)
    except EmptyPage:
        secrets = paginator.page(paginator.num_pages)
    return render(request,"secret_list.html",{"secrets":secrets,'item_page_offset': secrets.paginator.num_pages - secrets.number})

#문의하기 생성
@login_required
def secret_create(request):
    if request.method=="POST":
        form = SecretForm(request.POST, request.FILES)
        if form.is_valid():
            secret = form.save(commit=False)
            secret.created_at = timezone.now()
            secret.author=request.user
            secret.save()
            return redirect('secret_list')
    elif request.method=="GET":
        form = SecretForm()
        return render(request, "secret_create.html",{"form":form})

#문의하기 자세히보기
@login_required
def secret_detail(request,id):
    secret = get_object_or_404(SecretBorad, pk=id)
    secretcomments = SecretComment.objects.filter(secretborad=secret.id)
    if secret.private and secret.author != request.user:
        messages.error(request, '비밀글은 글 작성자만 볼 수 있습니다.')
        return redirect('secret_list')
    else:
        return render(request,"secret_detail.html",{"secret":secret,"secretcomments":secretcomments})

#문의하기 삭제
@login_required
def secret_delete(request,id):
    secret = get_object_or_404(SecretBorad,pk=id)
    if secret.author != request.user:
        return redirect("main")
    secret.delete()
    return redirect("secret_list")

board/templates/comment_update.html
<!-- 2015244055 김성민 
댓글 수정페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
{% block head %}
  <style>

</style>
  <title>Full Width Pics - Start Bootstrap Template</title>
{% endblock %}

</head>

<body>
    {% block header %}
    <article>
        <div class="container" role="main">
                <br>
                        <h2>댓글 수정하기</h2>
                        <br>                
                        <form action="{% url 'comment_update' comment.id %}" method="POST">
                            {% csrf_token %}
                <div class="mb-3">
                    <label for="content">댓글</label>
                    <textarea class="form-control" rows="5" name="message" required>{{ comment.message }}</textarea>
                </div>
                                   <input class="btn btn-success" type="submit" value="수정">

   </form>
<br>
</div>


{% endblock %}
</body>
</html>

board/templates/post_create.html
<!-- 2015244055 김성민 
자유게시판 작성 페이지-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
</head>
{% endblock %}
<body>
{% block header %}
<article>

    <div class="container" role="main">
<br>
        <h2>게시판 글 쓰기</h2>
        <br>
        <form name="form" id="form" role="form" method="POST" action="{% url 'post_create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title">제목</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해 주세요" required>
            </div>
            <div class="mb-3">
                <label for="content">내용</label>
                <textarea class="form-control" rows="5" name="content" id="content" placeholder="내용을 입력해 주세요" required></textarea>
            </div>
            <div class="mb-3">
                <label for="image">이미지</label>
                <input type="file" placeholder="파일을 선택하세요. " name="image" id="id_image" class="form-control"/>
            </div>
            <button type="submit" class="btn btn-success" id="btnSave">작성</button>
        </form>
<br>
    </div>
</article>
        {% endblock %}
</body>
</html>

board/templates/post_detail.html
<!-- 2015244055 김성민 
자유게시판 자세히 페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
<style>
    .btn-danger{
        color: blue;
    }
</style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
{% endblock %}
</head>
<body>
{% block header %}

<br>
<div class="row">
        <div class="col-xs-2 col-md-2"></div>
        <div class="col-xs-8 col-md-8">
            <br>
        <h2 class="text-center">게시글 보기</h2>
        <br>
        <div class="table table-responsive">
            <table class="table">
            <tr>
                <th class="success">글번호</th>
                <td>{{ post.id }}</td>
            </tr>
              
            
            <tr>
                <th class="success">작성자</th>
                <td>{{ post.author }}</td>
                 </tr>
        <tr>
            <th class="success">작성일</th>
            <td colspan="3">{{ post.created_at }}</td>
        
        </tr>
            
            <tr>
                <th class="success">제목</th>
                <td colspan="3">{{ post.title }}</td>
            </tr>
            
            <tr>
                <th class="success">글 내용</th>
                <td colspan="3">{{ post.content }}</td>
                {% if post.image.url is not None %}
<img src="{{ post.image.url }}" alt="" width="150px">
    {% endif %}

            </tr>
            
            <tr>
                <td colspan="4" class="text-center">
                    <a href="{% url 'post_update' post.id %}" class="btn btn-warning">수정하기</a>
    <a href="{% url 'post_delete' post.id %}" class="btn btn-danger" onclick="return confirm('정말 삭제하시겠습니까?')">삭제하기</a>
    <a class="btn btn-primary" href="{% url 'post_list' %}">목록보기</a>                </td>
            </tr>
        
           

            
            </table>
            <div class="card my-4">
                    <h5 class="card-header">댓글</h5>
                    <div class="card-body">
                            <form action="{% url 'comment_create' post.id %}" method="POST">
                                    {% csrf_token %}
                            <input type="text" class="form-group" name="message" required>
<br>
                            <input type="submit" class="btn btn-success"  value="답글 쓰기" >
                                                </form>
                    </div>
                </div>
                <table class="table">
                        {% for comment in comments %}
                             
            <tr>
                    <th class="success">작성자</th>
                    <td>{{ comment.author }}</td>
                     </tr>
            <tr>
                             
            <tr>
                    <th class="success">댓글 내용</th>
                    <td>{{ comment.message }}</td>
                     </tr>
            <tr>
                             
            <tr>
                    <th class="success">댓글 작성시간</th>
                    <td>{{ comment.created_at }}</td>
                     </tr>
            <tr>
                    {% if comment.author == request.user %}    
                    
            <tr>
                    <td colspan="3" class="text-center">
                     <span>
                    <form action="{% url 'comment_update' comment.id %}" style="    display: inline;" >
                            <input class="btn btn-warning" type="submit" value="댓글 수정"style="color:blue;">
                        </form>

                            <form action="{% url 'comment_delete' comment.id %}" method="POST" style="display: inline;">
                                    {% csrf_token %}
                                            <input type="submit" value="댓글 삭제" class="btn btn-danger" onclick="return confirm('정말 삭제하시겠습니까?')" >
                                        </form>    </span>
                  </td>
                </tr>
                            
                            
                                  
                    {% endif %}
                    
{% endfor %} 
                </table>
        </div>
        
        </div>
    </div>
    {% endblock %}


</body>
</html>

board/templates/post_list.html
<!-- 2015244055 김성민 
자유게시판 목록 페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
    <style>
    .text-btn{
      font-size:25px;
      font-weight: 550;
    }
    </style>
{% endblock %}
</head>
<body>
{% block header %}
<div class="container">
    <h1 class="mt-4 mb-3"><b>자유게시판</b></h1>          
    <form action="" method="GET">
          <input type="text" name="list" style="border:1px solid grey;">
          <input type="submit" value="글찾기" class = "btn btn-default"  style="border:1px solid grey;">
    </form>
  <table class ="table table-hover">
        <thead>
          <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성한 날짜</th>
            <th>댓글수</th>
          
          </tr>
        </thead>
        <tbody>
        <tr>
            {% for borad in borads %}
          <td>{{ borad.id }}</td>
          <td><a href="{% url 'post_detail' borad.id %}">{{ borad.title }}</a></td>
          <td>{{ borad.author }}</td>
          <td>{{ borad.created_at }}</td>
          <td>{{ borad.comments.count }}</td>
        </tr>
        </tbody>
                      {% endfor %}

      </table>
    <br>
    <a class = "btn btn-success" href="{% url 'post_create' %}">게시판 생성</a>
    <br>
    <br>
    <div class = "text-center">
    {% if borads.has_previous %}
            {% if borads.number > 2 %}
                <a class="button text-btn" href="?page=1">1</a>
                &nbsp;
            {% endif %}
                <a class="button text-btn" href="?page={{ borads.number|add:-1 }}">{{ borads.number|add:-1 }}</a>
                &nbsp;

            {% endif %}
            &nbsp;

            {% if borads.has_next %}
                <a class="button text-btn" href="?page={{ borads.number|add:1 }}">{{ borads.number|add:1 }}</a>
            {% if item_page_offset > 1 %}
            &nbsp;
                <a class="button text-btn" href="?page={{ borads.paginator.num_pages }}">{{ borads.paginator.num_pages }}</a>
            {% endif %}
            {% endif %}
           </div>
</div>
<br>
{% endblock %}

{% block footer %}
{% endblock %}  
</body>
</html>

board/templates/post_update.html
<!-- 2015244055 김성민 
자유게시판 수정 페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
    {% endblock %}
</head>
<body>
        {% block header %}
        <article>
        <div class="container" role="main">
                <br>
                        <h2>게시판 글 수정하기</h2>
                        <br>                
        <form action="{% url 'post_update' post.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                    <label for="title">제목</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해 주세요" value="{{ post.title }}" required>
                </div>
                <div class="mb-3">
                    <label for="content">내용</label>
                    <textarea class="form-control" rows="5" name="content" id="content" placeholder="내용을 입력해 주세요" required>{{ post.title }}</textarea>
                </div>
                <div class="mb-3">
                    <label for="image">이미지</label>
                    <input type="file" placeholder="파일을 선택하세요. " name="image" id="id_image" class="form-control" value="{{ post.image }}"/>
                </div>
                <button type="submit" class="btn btn-success" id="btnSave">작성</button>
            <input type="button" class="btn btn-primary" value="뒤로가기" onclick="history.back(-1);">
            
                </form>
                <br>
                </div>
            </article>
                {% endblock %}
</body>
</html>

board/templates/secret_create.html
<!-- 2015244055 김성민 
문의하기 생성 페이지 
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
</head>
{% endblock %}
<body>
{% block header %}
<article>

    <div class="container" role="main">
<br>
        <h2>건의하기</h2>
        <br>
        <form name="form" id="form" role="form" method="POST" action="{% url 'secret_create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title">제목</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해 주세요" required>
            </div>
            <div class="mb-3">
                <label for="content">내용</label>
                <textarea class="form-control" rows="5" name="content" id="content" placeholder="내용을 입력해 주세요" required></textarea>
            </div>
            <div class="mb-3">
                <label for="image">이미지</label>
                <input type="file" placeholder="파일을 선택하세요. " name="image" id="id_image" class="form-control"/>
            </div>
            <div><label for="id_private">비밀글 체크</label> 
                <input type="checkbox" name="private" id="id_private"></div>

            <button type="submit" class="btn btn-success" id="btnSave">작성</button>

        </form>
<br>
    </div>
</article>
        {% endblock %}
</body>
</html>

board/templates/secret_detail.html
<!-- 2015244055 김성민 
문의하기 자세히 페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
<style>
    .btn-danger{
        color: blue;
    }
</style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
{% endblock %}
</head>
<body>
{% block header %}

<br>
<div class="row">
        <div class="col-xs-2 col-md-2"></div>
        <div class="col-xs-8 col-md-8">
            <br>
        <h2 class="text-center">건의사항</h2>
        <br>
        <div class="table table-responsive">
            <table class="table">
            <tr>
                <th class="success">글번호</th>
                <td>{{ secret.id }}</td>
            </tr>
              
            
            <tr>
                <th class="success">작성자</th>
                <td>{{ secret.author }}</td>
                 </tr>
        <tr>
            <th class="success">작성일</th>
            <td colspan="3">{{ secret.created_at }}</td>
        
        </tr>
            
            <tr>
                <th class="success">제목</th>
                <td colspan="3">{{ secret.title }}</td>
            </tr>
            
            <tr>
                <th class="success">글 내용</th>
                <td colspan="3">{{ secret.content }}</td>
                {% if secret.image.url is not None %}
<img src="{{secret.image.url }}" alt="" width="150px">
    {% endif %}

            </tr>
            
            <tr>
                <td colspan="4" class="text-center">
    <a href="{% url 'secret_delete' secret.id %}" class="btn btn-danger" onclick="return confirm('정말 삭제하시겠습니까?')">삭제하기</a>
    <a class="btn btn-primary" href="{% url 'secret_list' %}">목록보기</a>                </td>
            </tr>
        
        </table>
        <table class="table">
                {% for secretcomment in secretcomments %}
                     
    <tr>
            <th class="success">작성자</th>
            <td>{{ secretcomment.author }}</td>
             </tr>
    <tr>
                     
    <tr>
            <th class="success">댓글 내용</th>
            <td>{{ secretcomment.message }}</td>
             </tr>
    <tr>
                     
    <tr>
            <th class="success">댓글 작성시간</th>
            <td>{{ secretcomment.created_at }}</td>
             </tr>
    
             
         </table>
         {% endfor %}
        
    </table>
    </div>
         </div>
         </div>
         </div>
    {% endblock %}

</body>
</html>

board/templates/secret_list.html
<!-- 2015244055 김성민 
문의하기 목록 페이지
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>선문대학교 셔틀버스</title>
    <style>
        .text-btn{
      font-size:25px;
      font-weight: 550;
    }
    </style>
{% endblock %}
</head>
<body>
{% block header %}


   <div class="container"  >
      <h1 class="mt-4 mb-3"><b>건의사항</b></h1>          
      <form action="" method="GET">
            <input type="text" name="list" style="border:1px solid grey;">
            <input type="submit" value="글찾기" class = "btn btn-default"  style="border:1px solid grey;">
      </form>
      <table class ="table table-hover">
        <thead>
          <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성한 날짜</th>
            <th>비밀체크</th>
          
          </tr>
        </thead>
        <tbody>
        <tr>
            {% for secret in secrets %}
     
          <td>{{ secret.id }}</td>
          <td><a href="{% url 'secret_detail' secret.id %}">{{ secret.title }}</a></td>
          <td>{{ secret.author }}</td>
          <td>{{ secret.created_at }}</td>
          {% if secret.private %}

          <td class="fa fa-lock" aria-hidden="true"></td>
             {% else %}
             <td></td>
             {% endif %}
        </tr>
        </tbody>
      

                      {% endfor %}

      </table>
    <br>
    <a class = "btn btn-success" href="{% url 'secret_create' %}">건의하기</a>
    <br>
    <br>

    <div class = "text-center">
        {% if secrets.has_previous %}
                {% if secrets.number > 2 %}
                    <a class="button text-btn" href="?page=1">1</a>
                    &nbsp;
                {% endif %}
                    <a class="button text-btn" href="?page={{ secrets.number|add:-1 }}">{{ secrets.number|add:-1 }}</a>
                    &nbsp;
    
                {% endif %}
                &nbsp;
    
                {% if secrets.has_next %}
                    <a class="button text-btn" href="?page={{ secrets.number|add:1 }}">{{ secrets.number|add:1 }}</a>
                {% if item_page_offset > 1 %}
                &nbsp;
                    <a class="button text-btn" href="?page={{ secrets.paginator.num_pages }}">{{ secrets.paginator.num_pages }}</a>
                {% endif %}
                {% endif %}
               </div>
</div>
<br>
{% endblock %}

{% block footer %}
{% endblock %}  
</body>
</html>